Testing ElevatedButton
Gustavoz9/teste-de-widget pull request #1
Opened 2022-07-25 15:17 UTC by Gustavoz9

2022-07-25 16:19 UTC, carlosWarren requested changes

2022-07-25 16:19 UTC, carlosWarren commented on lib/component/Button.dart
> +  }
Ele poderia ser um StatelesWidget

2022-07-25 16:19 UTC, carlosWarren commented on lib/component/Button.dart
> +          backgroundColor: widget.value == true
Nao precisa verificar se ele é igual a true da pra usar  widget.value ?

2022-07-25 16:19 UTC, carlosWarren commented on test/widget_test.dart
> +  testWidgets('must call back a functional widget',
A descrição do teste nao fica tao claro o q esta testando ..., se é um botão ou algo.
Link sobre nome de testes: https://www.notion.so/warrenbrasil/Testes-3799f27be42945c49035d9b892b18d40#c537574565c64b9194d3248e49dd23a3

2022-08-01 17:45 UTC, Gustavoz9 commented on lib/component/Button.dart
> +  }
Mudei para o StatelessWidget

2022-08-01 17:45 UTC, Gustavoz9 commented on lib/component/Button.dart
> +          backgroundColor: widget.value == true
Sim acabei de mudar isso

2022-08-01 17:48 UTC, Gustavoz9 commented on test/widget_test.dart
> +  testWidgets('must call back a functional widget',
Mudei para "WHEN button click THEN return Value" 
escolhi esse formato com base no exemplo do notion

2022-08-01 18:42 UTC, merged